import { HugeiconsIcon, type HugeiconsIconProps } from "@hugeicons/react";
import {
  Home01Icon,
  Message01Icon,
  Radar02Icon,
  HelpCircleIcon,
  Book01Icon,
  SlidersHorizontalIcon,
  Settings01Icon,
  Logout01Icon,
  ChevronDownIcon,
  ChevronRightIcon,
  AddCircleIcon,
  CheckIcon,
  Loading03Icon,
  ImageAdd01Icon,
  CircleCheckIcon,
  AlertCircleIcon,
  CancelCircleIcon,
  InformationCircleIcon,
  TriangleIcon,
  Copy01Icon,
  ExternalLinkIcon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowReloadHorizontalIcon,
  ArrowUpRight01Icon,
  ArrowDownRight01Icon,
  LockIcon,
  EyeIcon,
  EyeOffIcon,
  User03Icon,
  Search01Icon,
  Notification03Icon,
  CreditCardIcon,
  Mail01Icon,
  More03Icon,
  AiMagicIcon,
  StarIcon,
  StarHalfIcon,
  KanbanIcon,
  Cancel01Icon,
  ChevronUpIcon,
  GripVerticalIcon,
  Clock01Icon,
  SparklesIcon,
  Sun01Icon,
  MoonIcon,
  ComputerIcon,
  Delete02Icon,
} from "@hugeicons/core-free-icons";

type IconProps = Omit<HugeiconsIconProps, "icon">;

function createIcon(icon: HugeiconsIconProps["icon"]) {
  const Component = (props: IconProps) => <HugeiconsIcon icon={icon} {...props} />;
  Component.displayName = "Icon";

  return Component;
}

export const Icons = {
  home: createIcon(Home01Icon),
  message: createIcon(Message01Icon),
  radar: createIcon(Radar02Icon),
  help: createIcon(HelpCircleIcon),
  book: createIcon(Book01Icon),
  slidersHorizontal: createIcon(SlidersHorizontalIcon),
  settings: createIcon(Settings01Icon),
  logout: createIcon(Logout01Icon),
  chevronDown: createIcon(ChevronDownIcon),
  chevronRight: createIcon(ChevronRightIcon),
  circlePlus: createIcon(AddCircleIcon),
  check: createIcon(CheckIcon),
  loading: createIcon(Loading03Icon),
  imageAdd: createIcon(ImageAdd01Icon),
  circleCheck: createIcon(CircleCheckIcon),
  alertCircle: createIcon(AlertCircleIcon),
  cancelCircle: createIcon(CancelCircleIcon),
  info: createIcon(InformationCircleIcon),
  triangleAlert: createIcon(TriangleIcon),
  copy: createIcon(Copy01Icon),
  externalLink: createIcon(ExternalLinkIcon),
  arrowLeft: createIcon(ArrowLeft01Icon),
  arrowRight: createIcon(ArrowRight01Icon),
  refresh: createIcon(ArrowReloadHorizontalIcon),
  trendUp: createIcon(ArrowUpRight01Icon),
  trendDown: createIcon(ArrowDownRight01Icon),
  lock: createIcon(LockIcon),
  eye: createIcon(EyeIcon),
  eyeOff: createIcon(EyeOffIcon),
  user: createIcon(User03Icon),
  search: createIcon(Search01Icon),
  bell: createIcon(Notification03Icon),
  creditCard: createIcon(CreditCardIcon),
  mail: createIcon(Mail01Icon),
  moreHorizontal: createIcon(More03Icon),
  aiMagic: createIcon(AiMagicIcon),
  star: createIcon(StarIcon),
  starHalf: createIcon(StarHalfIcon),
  board: createIcon(KanbanIcon),
  x: createIcon(Cancel01Icon),
  chevronUp: createIcon(ChevronUpIcon),
  gripVertical: createIcon(GripVerticalIcon),
  clock: createIcon(Clock01Icon),
  sparkles: createIcon(SparklesIcon),
  sun: createIcon(Sun01Icon),
  moon: createIcon(MoonIcon),
  monitor: createIcon(ComputerIcon),
  trash: createIcon(Delete02Icon),
};
